export interface Monster{
    "slug"?:string,
    "name"?:string,
    "size"?:string,
    "type"?:string,
    "subtype"?:string,
    "group"?:string,
    "alignment"?:string,
    "armor_class"?:number,
    "armor_desc"?:string,
    "hit_points"?:number,
    "hit_dice"?:string,
    "speed": {
        "walk"?:number,
        "fly"?:number,
        "swim"?:number,
    },
    "strength"?:number,
    "dexterity"?:number,
    "constitution"?:number,
    "intelligence"?:number,
    "wisdom"?:number,
    "charisma"?:number,
    "strength_save"?:number,
    "dexterity_save"?:number,
    "constitution_save"?:number,
    "intelligence_save"?:number,
    "wisdom_save"?:number,
    "charisma_save"?:number,
    "perception"?:number,
    "damage_vulnerabilities"?:string,
    "damage_resistances"?:string,
    "damage_immunities"?:string,
    "condition_immunities"?:string,
    "senses"?:string,
    "languages"?:string,
    "challenge_rating"?:any,
    "actions":{
        "name"?:string,
        "desc"?:string,
        "attack_bonus"?:number,
        "damage_dice"?:string,
        "damage_bonus"?:number
    }[],
    "reactions"?:string,
    "legendary_actions"?:{
        "name"?:string,
        "desc"?:string
    }[],
    "special_abilities"?:{
        "name"?:string,
        "desc"?:string
    }[],
    "document_slug"?:string
    "amountInParty"?:number
}